# DAY 1

https://numpy.org/doc/stable/user/basics.indexing.html

In [1]:
import numpy as np

a1D = np.array([1,2,3,4])
a1D

array([1, 2, 3, 4])

In [2]:
a2D = np.array([[1,2],[3,4]])
a2D

array([[1, 2],
       [3, 4]])

In [3]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

 The 1D array creation functions e.g. numpy.linspace and numpy.arange generally need at least two inputs, start and stop.

numpy.arange creates arrays with regularly incrementing values.

In [4]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
# numpy.linspace will create arrays with a specified number of elements,
#  and spaced equally between the specified beginning and end values.
# For example:

import numpy as np
np.linspace(1., 4., 6)
array([1. ,  1.6,  2.2,  2.8,  3.4,  4. ])

# ADVANTAGE
# that you guarantee the number of elements and the starting and end point. The previous arange(start, stop, step) will not include the value stop.

2 - 2D array creation functions
The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define properties of special matrices represented as 2D arrays.

np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:

In [12]:
import numpy as np

# Creates an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Creates a diagonal matrix

np.diag([3,3,3])

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [14]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [15]:
np.diag([1, 2, 3], 0)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
a = np.array([[1,2],[3,4]])
np.diag(a)

array([1, 4])

In [17]:
# # vander(x, n) defines a Vandermonde matrix as a 2D NumPy
#  array.
#  Each column of the Vandermonde matrix
#  is a decreasing power of the input 1D array
#  or list or tuple, x where the highest polynomial order is n-1.
#  This array creation routine is helpful in generating linear least squares models, as such:

import numpy as np

np.vander(np.linspace(0,2,5),2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [18]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [19]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [ ]:
# 3. General ndarray creation functions

The ndarray creation functions e.g. numpy.ones, numpy.zeros, and random define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

In [20]:
# numpy.zeros will create an array filled with 0 values with the specified shape. The default dtype is float64:

import numpy as np

np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 2))

numpy.ones will create an array filled with 1 values. It is identical to zeros in all other respects as such:

In [21]:
import numpy as np

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
# The random method of the result of default_rng will create an array filled with random values between 0 and 1.
#  It is included with the numpy.random library.
# Below, two arrays are created with shapes (2,3) and (2,3,2), respectively.
# The seed is set to 42 so you can reproduce these pseudorandom numbers:



import numpy as np

from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [25]:
default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

# 3) Replicating, joining, or mutating existing arrays

Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy the array, otherwise the variable is a view into the original array. Consider the following example:

In [31]:
import numpy as np

a = np.array([1,2,3,4,5,6])

# This is a view, not a copy
b = a[:2]


b   =+ 1

print('a=',a, 'b=',b)

a= [1 2 3 4 5 6] b= 1


In [30]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [32]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)
# a =  [1 2 3 4] b =  [2 3]

a =  [1 2 3 4] b =  [2 3]


There are a number of routines to join existing arrays e.g. numpy.vstack, numpy.hstack, and numpy.block. Here is an example of joining four 2-by-2 arrays into a 4-by-4 array using block

In [36]:
import numpy as np

A = np.ones((2,2))
A

B = np.eye(2,2)
B

C = np.zeros((2,2))
C

D = np.diag((-3,-4))
D

np.block([[A,B],[C,D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])